package com.example.demo;

import jakarta.persistence.*; // Import for JPA annotations related to persistence and database interaction

@Entity // Marks this class as a JPA entity, which will be mapped to a database table
@Table(name = "users") // Specifies the table name in the database
public class User {

    @Id // Marks this field as the primary key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Specifies that the ID will be auto-generated by the database
    private Long id;

    @Column(unique = true, nullable = false) // Ensures the email is unique and cannot be null
    private String email;

    private String gender; // Gender of the user
    private int age; // Age of the user
    private String levelOfStudy; // Level of education (e.g., undergraduate, graduate)
    private String affiliation; // User's affiliation (e.g., university or company)
    private String password; // User's password (typically hashed)

    @Column(nullable = false, columnDefinition = "TINYINT(1) DEFAULT 0") // 0 or 1 to track if the user watched the videos
    private int watchedTheVideos;

    @Column(nullable = false, columnDefinition = "TINYINT(1) DEFAULT 0") // 0 or 1 to track if the user has taken the survey
    private int takenTheSurvey;

    @Column(nullable = false, columnDefinition = "INT DEFAULT 0") // Stores the index of the last watched video
    private int lastWatchedVideo;

    public User() {}

    // Constructor to initialize all fields of the User class
    public User(String email, String gender, int age, String levelOfStudy, String affiliation, String password, int watchedTheVideos, int takenTheSurvey, int lastWatchedVideo) {
        this.email = email;
        this.gender = gender;
        this.age = age;
        this.levelOfStudy = levelOfStudy;
        this.affiliation = affiliation;
        this.password = password;
        this.watchedTheVideos = watchedTheVideos;
        this.takenTheSurvey = takenTheSurvey;
        this.lastWatchedVideo = lastWatchedVideo;
    }

    // Getters and Setters for each field
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getGender() { return gender; }
    public void setGender(String gender) { this.gender = gender; }

    public int getAge() { return age; }
    public void setAge(int age) { this.age = age; }

    public String getLevelOfStudy() { return levelOfStudy; }
    public void setLevelOfStudy(String levelOfStudy) { this.levelOfStudy = levelOfStudy; }

    public String getAffiliation() { return affiliation; }
    public void setAffiliation(String affiliation) { this.affiliation = affiliation; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }

    public int getWatchedTheVideos() { return watchedTheVideos; }
    public void setWatchedTheVideos(int watchedTheVideos) { this.watchedTheVideos = watchedTheVideos; }

    public int getTakenTheSurvey() { return takenTheSurvey; }
    public void setTakenTheSurvey(int takenTheSurvey) { this.takenTheSurvey = takenTheSurvey; }

    public int getLastWatchedVideo() { return lastWatchedVideo; }
    public void setLastWatchedVideo(int lastWatchedVideo) { this.lastWatchedVideo = lastWatchedVideo; }
}
