# Generated by Django 5.1.7 on 2025-03-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=255)),
                ('agent_name', models.CharField(max_length=100)),
                ('attribute', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('ranking', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('selected_gender', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('level_of_study', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('watched_the_videos', models.BooleanField(default=False)),
                ('last_watched_video', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
