# Generated by Django 5.1.7 on 2025-04-05 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('level_of_study', models.CharField(max_length=100)),
                ('affiliation', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('watched_the_videos', models.BooleanField(default=False)),
                ('last_watched_video', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='attributeranking',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attributeranking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genderselection',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='genderselection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='attributeranking',
            table='attribute_rankings',
        ),
        migrations.AlterModelTable(
            name='genderselection',
            table='gender_selections',
        ),
        migrations.AlterField(
            model_name='attributeranking',
            name='user_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.users'),
        ),
    ]
